import '../models/patient.dart';
import '../models/doctor.dart';
import '../models/appointment.dart';
import '../models/billing.dart';
import '../models/communication.dart';
import '../models/notification_item.dart';
import '../models/call_reminder.dart';

class MockClinicData {
  static final DateTime today = DateTime.now();
  static final DateTime tomorrow = today.add(const Duration(days: 1));

  static List<Doctor> getDoctors() {
    return [
      const Doctor(
        id: 'DOC-01',
        name: 'Dr. Rahul Sharma',
        specialization: 'Chief Dentist & Implantologist',
        qualification: 'BDS, MDS (Prosthodontics)',
        status: DoctorStatus.available,
        currentPatientName: null,
        nextAvailableTime: '10:30 AM',
        roomNumber: 'Operatory 1',
        phone: '+91 98201 11223',
        avatarInitials: 'RS',
        todayAppointmentsCount: 8,
        completedTodayCount: 3,
      ),
      const Doctor(
        id: 'DOC-02',
        name: 'Dr. Priya Mehta',
        specialization: 'Orthodontist & Pedodontist',
        qualification: 'BDS, MDS (Orthodontics)',
        status: DoctorStatus.inConsultation,
        currentPatientName: 'Aarav Sharma',
        nextAvailableTime: '11:15 AM',
        roomNumber: 'Operatory 2',
        phone: '+91 98202 22334',
        avatarInitials: 'PM',
        todayAppointmentsCount: 10,
        completedTodayCount: 4,
      ),
      const Doctor(
        id: 'DOC-03',
        name: 'Dr. Amit Shah',
        specialization: 'Endodontist (Root Canal Specialist)',
        qualification: 'BDS, MDS (Conservative Dentistry)',
        status: DoctorStatus.busy,
        currentPatientName: 'Neha Kapoor',
        nextAvailableTime: '11:45 AM',
        roomNumber: 'Operatory 3',
        phone: '+91 98203 33445',
        avatarInitials: 'AS',
        todayAppointmentsCount: 6,
        completedTodayCount: 2,
      ),
    ];
  }

  static List<Patient> getPatients() {
    return [
      Patient(
        id: 'P-1001',
        name: 'Aarav Sharma',
        phone: '+91 98765 43210',
        email: 'aarav.sharma@gmail.com',
        dateOfBirth: '14 May 1994',
        gender: 'Male',
        address: 'B-402, Green Glen Heights, Bellandur, Bengaluru',
        emergencyContact: 'Sunita Sharma (Mother) +91 98765 43219',
        assignedDoctorId: 'DOC-02',
        assignedDoctorName: 'Dr. Priya Mehta',
        lastVisit: '05 Sep 2026',
        nextAppointment: 'Today, 10:00 AM',
        totalVisits: 4,
        balanceDue: 1500.0,
        bloodGroup: 'B+',
        allergies: ['Penicillin'],
        notes: 'Patient experiences mild dental anxiety. Prefers topical anesthetic spray first.',
        registrationDate: DateTime(2025, 3, 12),
      ),
      Patient(
        id: 'P-1002',
        name: 'Neha Kapoor',
        phone: '+91 98112 34567',
        email: 'neha.kapoor@outlook.com',
        dateOfBirth: '22 Aug 1988',
        gender: 'Female',
        address: 'Villa 14, Palm Meadows, Whitefield, Bengaluru',
        emergencyContact: 'Rajesh Kapoor (Spouse) +91 98112 34568',
        assignedDoctorId: 'DOC-03',
        assignedDoctorName: 'Dr. Amit Shah',
        lastVisit: '12 Sep 2026',
        nextAppointment: 'Today, 10:30 AM',
        totalVisits: 6,
        balanceDue: 0.0,
        bloodGroup: 'O+',
        allergies: [],
        notes: 'Undergoing step-2 root canal treatment on lower right molar (#46).',
        registrationDate: DateTime(2024, 11, 20),
      ),
      Patient(
        id: 'P-1003',
        name: 'Rohan Singh',
        phone: '+91 97234 56789',
        email: 'rohan.singh@gmail.com',
        dateOfBirth: '03 Dec 1991',
        gender: 'Male',
        address: 'Flat 102, Silver Spring, HSR Layout, Bengaluru',
        emergencyContact: 'Pooja Singh (Wife) +91 97234 56780',
        assignedDoctorId: 'DOC-01',
        assignedDoctorName: 'Dr. Rahul Sharma',
        lastVisit: '18 Aug 2026',
        nextAppointment: 'Today, 11:00 AM',
        totalVisits: 2,
        balanceDue: 800.0,
        bloodGroup: 'A+',
        allergies: ['Latex sensitivity'],
        notes: 'Complained of food lodgement between upper left molars. Composite filling suggested.',
        registrationDate: DateTime(2026, 1, 15),
      ),
      Patient(
        id: 'P-1004',
        name: 'Ananya Patel',
        phone: '+91 96345 67890',
        email: 'ananya.patel@yahoo.com',
        dateOfBirth: '19 Oct 1999',
        gender: 'Female',
        address: 'House 88, 12th Main, Indiranagar, Bengaluru',
        emergencyContact: 'Meera Patel (Mother) +91 96345 67899',
        assignedDoctorId: 'DOC-02',
        assignedDoctorName: 'Dr. Priya Mehta',
        lastVisit: '25 Jul 2026',
        nextAppointment: 'Today, 11:30 AM',
        totalVisits: 5,
        balanceDue: 0.0,
        bloodGroup: 'AB+',
        allergies: [],
        notes: 'Routine aligners tracking checkup. Wearing tray #14.',
        registrationDate: DateTime(2025, 8, 5),
      ),
      Patient(
        id: 'P-1005',
        name: 'Mohit Bansal',
        phone: '+91 99012 34567',
        email: 'mohit.bansal@gmail.com',
        dateOfBirth: '10 Feb 1982',
        gender: 'Male',
        address: 'Tower C-903, Prestige Park, Koramangala, Bengaluru',
        emergencyContact: 'Renu Bansal (Spouse) +91 99012 34560',
        assignedDoctorId: 'DOC-01',
        assignedDoctorName: 'Dr. Rahul Sharma',
        lastVisit: '01 Sep 2026',
        nextAppointment: 'Today, 12:00 PM',
        totalVisits: 3,
        balanceDue: 2200.0,
        bloodGroup: 'O+',
        allergies: [],
        notes: 'Implant crown seating scheduled. Titanium abutment placed last month.',
        registrationDate: DateTime(2025, 6, 18),
      ),
      Patient(
        id: 'P-1006',
        name: 'Kavya Joshi',
        phone: '+91 98450 98765',
        email: 'kavya.joshi@gmail.com',
        dateOfBirth: '28 Jun 2003',
        gender: 'Female',
        address: 'Flat 5A, Alpine Eco, Marathahalli, Bengaluru',
        emergencyContact: 'Suresh Joshi (Father) +91 98450 98760',
        assignedDoctorId: 'DOC-02',
        assignedDoctorName: 'Dr. Priya Mehta',
        lastVisit: '10 Jun 2026',
        nextAppointment: 'Today, 02:30 PM',
        totalVisits: 1,
        balanceDue: 0.0,
        bloodGroup: 'A-',
        allergies: [],
        notes: 'First routine checkup & oral prophylaxis.',
        registrationDate: DateTime(2026, 6, 10),
      ),
      Patient(
        id: 'P-1007',
        name: 'Vikram Malhotra',
        phone: '+91 99887 76655',
        email: 'vikram.m@corporatemail.com',
        dateOfBirth: '15 Jul 1978',
        gender: 'Male',
        address: 'B-12, Defence Colony, Bengaluru',
        emergencyContact: 'Geeta Malhotra (Wife) +91 99887 76650',
        assignedDoctorId: 'DOC-01',
        assignedDoctorName: 'Dr. Rahul Sharma',
        lastVisit: '14 Aug 2026',
        nextAppointment: 'Tomorrow, 10:00 AM',
        totalVisits: 8,
        balanceDue: 0.0,
        bloodGroup: 'B+',
        allergies: [],
        notes: 'Full mouth ultrasonic scaling & polishing follow up.',
        registrationDate: DateTime(2024, 2, 10),
      ),
      Patient(
        id: 'P-1008',
        name: 'Sunita Rao',
        phone: '+91 91234 56781',
        email: 'sunita.rao@gmail.com',
        dateOfBirth: '08 Mar 1965',
        gender: 'Female',
        address: 'Plot 45, JP Nagar 3rd Phase, Bengaluru',
        emergencyContact: 'Girish Rao (Son) +91 91234 56789',
        assignedDoctorId: 'DOC-03',
        assignedDoctorName: 'Dr. Amit Shah',
        lastVisit: '20 Aug 2026',
        nextAppointment: 'Tomorrow, 11:30 AM',
        totalVisits: 4,
        balanceDue: 3500.0,
        bloodGroup: 'O+',
        allergies: ['NSAIDs / Ibuprofen'],
        notes: 'Diabetic patient. Check blood sugar report before surgical extractions.',
        registrationDate: DateTime(2025, 1, 9),
      ),
    ];
  }

  static List<Appointment> getAppointments() {
    final now = DateTime.now();
    final todayDate = DateTime(now.year, now.month, now.day);
    final tomorrowDate = todayDate.add(const Duration(days: 1));

    return [
      // TODAY'S APPOINTMENTS
      Appointment(
        id: 'APT-001',
        patientId: 'P-1001',
        patientName: 'Aarav Sharma',
        patientPhone: '+91 98765 43210',
        doctorId: 'DOC-02',
        doctorName: 'Dr. Priya Mehta',
        dateTime: todayDate.add(const Duration(hours: 10, minutes: 0)),
        timeString: '10:00 AM',
        appointmentType: 'Routine Checkup',
        durationMinutes: 30,
        status: AppointmentStatus.inProgress, // With Doctor
        tokenNumber: 'TK-01',
        roomNumber: 'Operatory 2',
        notes: 'Routine orthodontic bracket adjustment',
        checkInTime: todayDate.add(const Duration(hours: 9, minutes: 48)),
        waitMinutes: 12,
      ),
      Appointment(
        id: 'APT-002',
        patientId: 'P-1002',
        patientName: 'Neha Kapoor',
        patientPhone: '+91 98112 34567',
        doctorId: 'DOC-03',
        doctorName: 'Dr. Amit Shah',
        dateTime: todayDate.add(const Duration(hours: 10, minutes: 30)),
        timeString: '10:30 AM',
        appointmentType: 'Root Canal Consultation',
        durationMinutes: 45,
        status: AppointmentStatus.waiting,
        tokenNumber: 'TK-02',
        roomNumber: 'Operatory 3',
        notes: 'Sitting 2 of lower molar root canal',
        checkInTime: todayDate.add(const Duration(hours: 10, minutes: 15)),
        waitMinutes: 15,
      ),
      Appointment(
        id: 'APT-003',
        patientId: 'P-1003',
        patientName: 'Rohan Singh',
        patientPhone: '+91 97234 56789',
        doctorId: 'DOC-01',
        doctorName: 'Dr. Rahul Sharma',
        dateTime: todayDate.add(const Duration(hours: 11, minutes: 0)),
        timeString: '11:00 AM',
        appointmentType: 'Dental Filling',
        durationMinutes: 30,
        status: AppointmentStatus.checkedIn,
        tokenNumber: 'TK-03',
        roomNumber: 'Operatory 1',
        notes: 'Composite filling upper left tooth #25',
        checkInTime: todayDate.add(const Duration(hours: 10, minutes: 50)),
        waitMinutes: 10,
      ),
      Appointment(
        id: 'APT-004',
        patientId: 'P-1004',
        patientName: 'Ananya Patel',
        patientPhone: '+91 96345 67890',
        doctorId: 'DOC-02',
        doctorName: 'Dr. Priya Mehta',
        dateTime: todayDate.add(const Duration(hours: 11, minutes: 30)),
        timeString: '11:30 AM',
        appointmentType: 'Consultation',
        durationMinutes: 30,
        status: AppointmentStatus.arrived,
        tokenNumber: 'TK-04',
        roomNumber: 'Operatory 2',
        notes: 'Aligner assessment & digital scan',
        checkInTime: todayDate.add(const Duration(hours: 11, minutes: 22)),
        waitMinutes: 8,
      ),
      Appointment(
        id: 'APT-005',
        patientId: 'P-1005',
        patientName: 'Mohit Bansal',
        patientPhone: '+91 99012 34567',
        doctorId: 'DOC-01',
        doctorName: 'Dr. Rahul Sharma',
        dateTime: todayDate.add(const Duration(hours: 12, minutes: 0)),
        timeString: '12:00 PM',
        appointmentType: 'Follow-up',
        durationMinutes: 30,
        status: AppointmentStatus.confirmed,
        tokenNumber: 'TK-05',
        roomNumber: 'Operatory 1',
        notes: 'Post-implant evaluation',
      ),
      Appointment(
        id: 'APT-006',
        patientId: 'P-1006',
        patientName: 'Kavya Joshi',
        patientPhone: '+91 98450 98765',
        doctorId: 'DOC-02',
        doctorName: 'Dr. Priya Mehta',
        dateTime: todayDate.add(const Duration(hours: 14, minutes: 30)),
        timeString: '02:30 PM',
        appointmentType: 'Cleaning',
        durationMinutes: 30,
        status: AppointmentStatus.scheduled,
        tokenNumber: 'TK-06',
        roomNumber: 'Operatory 2',
        notes: 'Deep ultrasonic prophylaxis',
      ),

      // TOMORROW'S APPOINTMENTS
      Appointment(
        id: 'APT-101',
        patientId: 'P-1007',
        patientName: 'Vikram Malhotra',
        patientPhone: '+91 99887 76655',
        doctorId: 'DOC-01',
        doctorName: 'Dr. Rahul Sharma',
        dateTime: tomorrowDate.add(const Duration(hours: 10, minutes: 0)),
        timeString: '10:00 AM',
        appointmentType: 'Cleaning',
        durationMinutes: 45,
        status: AppointmentStatus.confirmed,
        tokenNumber: 'TK-T1',
        roomNumber: 'Operatory 1',
        notes: 'Periodic maintenance & polish',
      ),
      Appointment(
        id: 'APT-102',
        patientId: 'P-1008',
        patientName: 'Sunita Rao',
        patientPhone: '+91 91234 56781',
        doctorId: 'DOC-03',
        doctorName: 'Dr. Amit Shah',
        dateTime: tomorrowDate.add(const Duration(hours: 11, minutes: 30)),
        timeString: '11:30 AM',
        appointmentType: 'Root Canal Consultation',
        durationMinutes: 45,
        status: AppointmentStatus.scheduled,
        tokenNumber: 'TK-T2',
        roomNumber: 'Operatory 3',
        notes: 'X-ray evaluation of tooth #16 pain',
      ),
      Appointment(
        id: 'APT-103',
        patientId: 'P-1001',
        patientName: 'Aarav Sharma',
        patientPhone: '+91 98765 43210',
        doctorId: 'DOC-02',
        doctorName: 'Dr. Priya Mehta',
        dateTime: tomorrowDate.add(const Duration(hours: 15, minutes: 0)),
        timeString: '03:00 PM',
        appointmentType: 'Follow-up',
        durationMinutes: 30,
        status: AppointmentStatus.confirmed,
        tokenNumber: 'TK-T3',
        roomNumber: 'Operatory 2',
        notes: 'Retainer tightness review',
      ),
    ];
  }

  static List<Invoice> getInvoices() {
    final now = DateTime.now();
    return [
      Invoice(
        id: 'INV-001',
        invoiceNumber: 'INV-2026-0841',
        patientId: 'P-1001',
        patientName: 'Aarav Sharma',
        patientPhone: '+91 98765 43210',
        doctorId: 'DOC-02',
        doctorName: 'Dr. Priya Mehta',
        date: now.subtract(const Duration(hours: 2)),
        items: const [
          InvoiceItem(description: 'Comprehensive Orthodontic Evaluation', quantity: 1, unitPrice: 1500.0, amount: 1500.0),
          InvoiceItem(description: 'Digital OPG Panoramic X-Ray', quantity: 1, unitPrice: 1000.0, amount: 1000.0),
          InvoiceItem(description: 'Ceramic Bracket Adjustment & Archwire', quantity: 1, unitPrice: 2000.0, amount: 2000.0),
        ],
        subtotal: 4500.0,
        discount: 500.0,
        tax: 0.0,
        totalAmount: 4000.0,
        paidAmount: 2500.0,
        balanceAmount: 1500.0,
        status: PaymentStatus.partial,
        paymentMethod: 'UPI (Google Pay)',
        transactionRef: 'UPI-9843102488',
        notes: 'Balance ₹1,500 due on next appointment visit.',
      ),
      Invoice(
        id: 'INV-002',
        invoiceNumber: 'INV-2026-0842',
        patientId: 'P-1002',
        patientName: 'Neha Kapoor',
        patientPhone: '+91 98112 34567',
        doctorId: 'DOC-03',
        doctorName: 'Dr. Amit Shah',
        date: now.subtract(const Duration(hours: 4)),
        items: const [
          InvoiceItem(description: 'Single Sitting Rotary Root Canal Treatment (RCT)', quantity: 1, unitPrice: 6500.0, amount: 6500.0),
          InvoiceItem(description: 'Digital RVG Intraoral X-Ray', quantity: 2, unitPrice: 400.0, amount: 800.0),
          InvoiceItem(description: 'Post & Core Build Up', quantity: 1, unitPrice: 1500.0, amount: 1500.0),
        ],
        subtotal: 8800.0,
        discount: 300.0,
        tax: 0.0,
        totalAmount: 8500.0,
        paidAmount: 8500.0,
        balanceAmount: 0.0,
        status: PaymentStatus.paid,
        paymentMethod: 'Credit Card (HDFC)',
        transactionRef: 'TXN-HDFC-99124',
        notes: 'Paid in full at counter.',
      ),
      Invoice(
        id: 'INV-003',
        invoiceNumber: 'INV-2026-0843',
        patientId: 'P-1003',
        patientName: 'Rohan Singh',
        patientPhone: '+91 97234 56789',
        doctorId: 'DOC-01',
        doctorName: 'Dr. Rahul Sharma',
        date: now.subtract(const Duration(days: 1)),
        items: const [
          InvoiceItem(description: 'Class II Posterior Composite Restoration', quantity: 1, unitPrice: 1800.0, amount: 1800.0),
        ],
        subtotal: 1800.0,
        discount: 0.0,
        tax: 0.0,
        totalAmount: 1800.0,
        paidAmount: 1000.0,
        balanceAmount: 800.0,
        status: PaymentStatus.partial,
        paymentMethod: 'Cash',
        notes: 'Patient promised to clear ₹800 via UPI later today.',
      ),
      Invoice(
        id: 'INV-004',
        invoiceNumber: 'INV-2026-0844',
        patientId: 'P-1005',
        patientName: 'Mohit Bansal',
        patientPhone: '+91 99012 34567',
        doctorId: 'DOC-01',
        doctorName: 'Dr. Rahul Sharma',
        date: now.subtract(const Duration(days: 2)),
        items: const [
          InvoiceItem(description: 'Zirconia CAD/CAM Implant Crown', quantity: 1, unitPrice: 12000.0, amount: 12000.0),
          InvoiceItem(description: 'Custom Titanium Abutment Delivery', quantity: 1, unitPrice: 4500.0, amount: 4500.0),
        ],
        subtotal: 16500.0,
        discount: 500.0,
        tax: 0.0,
        totalAmount: 16000.0,
        paidAmount: 13800.0,
        balanceAmount: 2200.0,
        status: PaymentStatus.partial,
        paymentMethod: 'UPI (PhonePe)',
        transactionRef: 'UPI-771120098',
        notes: 'Crown cemented successfully with warranty card issued.',
      ),
      Invoice(
        id: 'INV-005',
        invoiceNumber: 'INV-2026-0845',
        patientId: 'P-1006',
        patientName: 'Kavya Joshi',
        patientPhone: '+91 98450 98765',
        doctorId: 'DOC-02',
        doctorName: 'Dr. Priya Mehta',
        date: now.subtract(const Duration(days: 3)),
        items: const [
          InvoiceItem(description: 'Ultrasonic Scaling & Air Polish', quantity: 1, unitPrice: 1500.0, amount: 1500.0),
          InvoiceItem(description: 'Topical Fluoride Varnish Application', quantity: 1, unitPrice: 800.0, amount: 800.0),
        ],
        subtotal: 2300.0,
        discount: 300.0,
        tax: 0.0,
        totalAmount: 2000.0,
        paidAmount: 2000.0,
        balanceAmount: 0.0,
        status: PaymentStatus.paid,
        paymentMethod: 'UPI (Paytm)',
        notes: 'Full settlement.',
      ),
    ];
  }

  static List<CallRecord> getCallRecords() {
    final now = DateTime.now();
    return [
      CallRecord(
        id: 'CALL-01',
        patientId: 'P-1001',
        patientName: 'Aarav Sharma',
        phoneNumber: '+91 98765 43210',
        timestamp: now.subtract(const Duration(minutes: 25)),
        durationSeconds: 114,
        direction: CallDirection.outgoing,
        status: CallStatus.answered,
        note: 'Confirmed arrival in 10 mins. Requested parking guidance.',
      ),
      CallRecord(
        id: 'CALL-02',
        patientId: 'P-1004',
        patientName: 'Ananya Patel',
        phoneNumber: '+91 96345 67890',
        timestamp: now.subtract(const Duration(minutes: 55)),
        durationSeconds: 78,
        direction: CallDirection.incoming,
        status: CallStatus.answered,
        note: 'Inquired if Dr. Priya Mehta has any delay today.',
      ),
      CallRecord(
        id: 'CALL-03',
        patientId: 'P-1007',
        patientName: 'Vikram Malhotra',
        phoneNumber: '+91 99887 76655',
        timestamp: now.subtract(const Duration(hours: 2, minutes: 10)),
        durationSeconds: 0,
        direction: CallDirection.outgoing,
        status: CallStatus.missed,
        note: 'Attempted reminder call for tomorrow 10 AM. Will send WhatsApp.',
      ),
      CallRecord(
        id: 'CALL-04',
        patientId: 'P-1003',
        patientName: 'Rohan Singh',
        phoneNumber: '+91 97234 56789',
        timestamp: now.subtract(const Duration(hours: 3)),
        durationSeconds: 142,
        direction: CallDirection.incoming,
        status: CallStatus.answered,
        note: 'Checked in regarding tooth sensitivity after previous filling.',
      ),
    ];
  }

  static List<MessageRecord> getMessageRecords() {
    final now = DateTime.now();
    return [
      MessageRecord(
        id: 'MSG-01',
        patientId: 'P-1001',
        patientName: 'Aarav Sharma',
        phoneNumber: '+91 98765 43210',
        channel: MessageChannel.whatsapp,
        message: 'Dear Aarav, your dental appointment with Dr. Priya Mehta is scheduled for today at 10:00 AM at SmileCare Dental Clinic. Please arrive 10 mins prior. See you soon!',
        templateCategory: 'Appointment Reminder',
        timestamp: now.subtract(const Duration(hours: 2)),
        status: MessageDeliveryStatus.read,
      ),
      MessageRecord(
        id: 'MSG-02',
        patientId: 'P-1002',
        patientName: 'Neha Kapoor',
        phoneNumber: '+91 98112 34567',
        channel: MessageChannel.sms,
        message: 'SmileCare: Payment of Rs. 8,500 received successfully for Invoice INV-2026-0842. Thank you for visiting Dr. Amit Shah.',
        templateCategory: 'Payment Reminder',
        timestamp: now.subtract(const Duration(hours: 3)),
        status: MessageDeliveryStatus.delivered,
      ),
      MessageRecord(
        id: 'MSG-03',
        patientId: 'P-1007',
        patientName: 'Vikram Malhotra',
        phoneNumber: '+91 99887 76655',
        channel: MessageChannel.whatsapp,
        message: 'Dear Vikram, this is a gentle reminder for your dental cleaning with Dr. Rahul Sharma tomorrow at 10:00 AM. Reply 1 to Confirm or 2 to Reschedule.',
        templateCategory: 'Appointment Reminder',
        timestamp: now.subtract(const Duration(hours: 1, minutes: 15)),
        status: MessageDeliveryStatus.delivered,
      ),
      MessageRecord(
        id: 'MSG-04',
        patientId: 'P-1005',
        patientName: 'Mohit Bansal',
        phoneNumber: '+91 99012 34567',
        channel: MessageChannel.sms,
        message: 'SmileCare: Gentle reminder that a pending balance of Rs. 2,200 is due on Invoice INV-2026-0844. Pay online via UPI or at reception desk.',
        templateCategory: 'Payment Reminder',
        timestamp: now.subtract(const Duration(days: 1)),
        status: MessageDeliveryStatus.sent,
      ),
    ];
  }

  static List<NotificationItem> getNotifications() {
    final now = DateTime.now();
    return [
      NotificationItem(
        id: 'NOTIF-01',
        title: 'Appointment in 15 Minutes',
        message: 'Aarav Sharma scheduled with Dr. Priya Mehta (Operatory 2) at 10:00 AM.',
        timestamp: now.subtract(const Duration(minutes: 5)),
        isRead: false,
        type: NotificationType.appointment,
      ),
      NotificationItem(
        id: 'NOTIF-02',
        title: 'Patient Checked In',
        message: 'Neha Kapoor has arrived and checked in at reception for Operatory 3.',
        timestamp: now.subtract(const Duration(minutes: 18)),
        isRead: false,
        type: NotificationType.checkIn,
      ),
      NotificationItem(
        id: 'NOTIF-03',
        title: 'Doctor is Available',
        message: 'Dr. Rahul Sharma has completed consultation and is now free.',
        timestamp: now.subtract(const Duration(minutes: 42)),
        isRead: false,
        type: NotificationType.doctorAvailable,
      ),
      NotificationItem(
        id: 'NOTIF-04',
        title: 'Payment Pending Alert',
        message: 'Invoice INV-2026-0841 for Aarav Sharma has an outstanding balance of ₹1,500.',
        timestamp: now.subtract(const Duration(hours: 1, minutes: 20)),
        isRead: true,
        type: NotificationType.paymentPending,
      ),
      NotificationItem(
        id: 'NOTIF-05',
        title: 'Tomorrow Schedule Reminder',
        message: '3 patients confirmed for tomorrow morning session with Dr. Rahul Sharma and Dr. Amit Shah.',
        timestamp: now.subtract(const Duration(hours: 3)),
        isRead: true,
        type: NotificationType.reminder,
      ),
    ];
  }

  static List<CallReminder> getCallReminders() {
    return [
      const CallReminder(
        id: 'REM-01',
        patientId: 'P-1001',
        patientName: 'Aarav Sharma',
        phoneNumber: '+91 98765 43210',
        appointmentDate: '21 Sep 2026',
        appointmentTime: '10:30 AM',
        doctorName: 'Dr. Priya Mehta',
        status: ReminderStatus.pending,
        lastAttempt: 'Not called',
        nextAttempt: 'Today before 12:00 PM',
        appointmentType: 'Routine Checkup',
        notes: 'Requested parking slot guidance earlier.',
      ),
      const CallReminder(
        id: 'REM-02',
        patientId: 'P-1007',
        patientName: 'Vikram Malhotra',
        phoneNumber: '+91 99887 76655',
        appointmentDate: '21 Sep 2026',
        appointmentTime: '10:00 AM',
        doctorName: 'Dr. Rahul Sharma',
        status: ReminderStatus.missed,
        lastAttempt: 'Today 09:15 AM - No Answer',
        nextAttempt: 'Call back at 01:30 PM',
        appointmentType: 'Cleaning & Scaling',
        notes: 'Sent WhatsApp reminder after missed call.',
      ),
      const CallReminder(
        id: 'REM-03',
        patientId: 'P-1008',
        patientName: 'Sunita Rao',
        phoneNumber: '+91 91234 56781',
        appointmentDate: '21 Sep 2026',
        appointmentTime: '11:30 AM',
        doctorName: 'Dr. Amit Shah',
        status: ReminderStatus.confirmed,
        lastAttempt: 'Today 09:40 AM - Answered',
        nextAttempt: 'Done (Confirmed)',
        appointmentType: 'Root Canal Consultation',
        notes: 'Confirmed will bring recent sugar reports.',
      ),
      const CallReminder(
        id: 'REM-04',
        patientId: 'P-1002',
        patientName: 'Neha Kapoor',
        phoneNumber: '+91 98112 34567',
        appointmentDate: '21 Sep 2026',
        appointmentTime: '02:00 PM',
        doctorName: 'Dr. Amit Shah',
        status: ReminderStatus.pending,
        lastAttempt: 'Not called',
        nextAttempt: 'Today by 11:30 AM',
        appointmentType: 'Root Canal Sitting 2',
      ),
      const CallReminder(
        id: 'REM-05',
        patientId: 'P-1003',
        patientName: 'Rohan Singh',
        phoneNumber: '+91 97234 56789',
        appointmentDate: '21 Sep 2026',
        appointmentTime: '03:15 PM',
        doctorName: 'Dr. Rahul Sharma',
        status: ReminderStatus.confirmed,
        lastAttempt: 'Yesterday 05:00 PM - Confirmed',
        nextAttempt: 'Done (Confirmed)',
        appointmentType: 'Dental Filling',
      ),
      const CallReminder(
        id: 'REM-06',
        patientId: 'P-1004',
        patientName: 'Ananya Patel',
        phoneNumber: '+91 96345 67890',
        appointmentDate: '21 Sep 2026',
        appointmentTime: '04:00 PM',
        doctorName: 'Dr. Priya Mehta',
        status: ReminderStatus.pending,
        lastAttempt: 'Not called',
        nextAttempt: 'Today by 02:00 PM',
        appointmentType: 'Aligner Review',
      ),
      const CallReminder(
        id: 'REM-07',
        patientId: 'P-1005',
        patientName: 'Mohit Bansal',
        phoneNumber: '+91 99012 34560',
        appointmentDate: '21 Sep 2026',
        appointmentTime: '04:45 PM',
        doctorName: 'Dr. Rahul Sharma',
        status: ReminderStatus.missed,
        lastAttempt: 'Today 10:10 AM - Line Busy',
        nextAttempt: 'Retry required at 02:30 PM',
        appointmentType: 'Implant Seating',
        notes: 'Spouse answered; patient in office meeting.',
      ),
      const CallReminder(
        id: 'REM-08',
        patientId: 'P-1006',
        patientName: 'Kavya Joshi',
        phoneNumber: '+91 98450 98765',
        appointmentDate: '21 Sep 2026',
        appointmentTime: '05:30 PM',
        doctorName: 'Dr. Priya Mehta',
        status: ReminderStatus.confirmed,
        lastAttempt: 'Today 10:20 AM - Confirmed',
        nextAttempt: 'Done (Confirmed)',
        appointmentType: 'Routine Cleaning',
      ),
    ];
  }
}
